### ISSUE TITLE
Installing on Linux Fails After Compilation with Clang

### ISSUE THREAD

**Issue by sanssecours** [vnmakarov/yaep#9]
# Steps to Reproduce the Problem

1. Clone the Repository

   ```sh
   git clone git clone https://github.com/vnmakarov/yaep.git
   ```

2. Compile and Install YAEP using Clang

   ```sh
   ./configure
   cd src
   make
   make test
   sudo make install
   ```

# Expected Result

The last command should work without problems.

# Actual Result

The last command fails printing the following output:

```
bison -y ./sgramm.y
mv y.tab.c sgramm.c
clang -c -g  -Ofast -DHAVE_CONFIG_H -I.. -I. -I. -DNDEBUG -fPIC -o C/yaep.o ../src/../src/yaep.c
make: clang: Command not found
make: *** [C/yaep.o] Error 127
```

# System Information

**OS:** Ubuntu Trusty Tahr
**Compiler:** Clang 5.0

# Additional Information

- [Travis Build Job](https://travis-ci.com/sanssecours/yaep/jobs/146364827)

**Comment by vnmakarov** [comment]
It looks like clang is not installed on the build machine.

**Comment by sanssecours** [comment]
Thank you for the quick response.

> It looks like clang is not installed on the build machine.

If that is the case, how could [Travis translate YAEP using clang++](https://travis-ci.com/sanssecours/yaep/jobs/146364827#L455-L456)?

**Comment by sanssecours** [comment]
I think I found the problem. It seems like [Travis changes `PATH` for super users](https://github.com/travis-ci/travis-ci/issues/1350). Thank you for your help.
